### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by gittestcoder** [rhaker/react-native-sms-android#1]
This module is really useful for me. Was wondering is there any plan to add iOS support in the future?

**Comment by rhaker** [comment]
Thanks for using the module. Apple doesn't support the functionality in this module (i.e. you can't send silent sms messages directly from an app). To send an sms in iOS, you can use the core Linking component in React Native. This approach forces the default messaging app to open. And then the user has to push the send button. The other approach is to use an external web services api to send the sms. There are companies like Twilio that provide this for iOS (see the react native twilio module). Good luck.

**Comment by gittestcoder** [comment]
I see, thanks for the reply.
