### ISSUE TITLE
For Android it work fine. How can we use it for both Android and IOS ?

### ISSUE THREAD

**Issue by shammus672agmailcom** [rhaker/react-native-sms-android#11]
AS we use react native for cross plat form app development. I want to develop a single app which work same on both android and ios. You recomend to use LinkingIOS component for ios. Please provide some sample example.

**Comment by rhaker** [comment]
For ios, try using the Linking component. Details are found here (https://facebook.github.io/react-native/docs/linking.html). LinkingIOS was a previous component that has been deprecated into the new version of RN. Basically, you just put the sms info into a link in the React Native form of a url like
url="sms:123456789&body=sometext" -- Stackoverflow probably has some exact examples
