### ISSUE TITLE
You should parse the phone number for digits only for best results

### ISSUE THREAD

**Issue by shammus672agmailcom** [rhaker/react-native-sms-android#12]
Using your work i want to fetch all mobile no having in 'sent', 'draft', 'outbox', 'failed', 'queued'. once. Now i am reviving all the records but multiple time (depend upon the messages). i want to receive all contacts once.

**Comment by rhaker** [comment]
Thanks for the comment. If I understand correctly, you should be able to parse the results in javascript after receiving. Just set up an array and then you can remove duplicates or parse for numbers using a regular expression. Apologies if I'm misunderstanding...
